### ISSUE TITLE
Login doesn't work

### ISSUE THREAD

**Issue by naoliv** [willemarcel/osmcha-django#19]
When clicking on `Login` (which points to http://osmcha.openstreetmap.com.br/social/login/openstreetmap/):

![](http://i.imgur.com/7ihhyjd.png)

**Comment by willemarcel** [comment]
Solved!

**Comment by naoliv** [comment]
Almost :-/
After granting access with OSM's oauth it fails in

`http://osmcha.openstreetmap.com.br/social/complete/openstreetmap/?oauth_token=XXXXXXX` with an Internal Server Error

**Comment by alexandre-mbm** [comment]
For me also.

**Comment by willemarcel** [comment]
@naoliv @alexandre-mbm Check it now please.

**Comment by naoliv** [comment]
Seems good now :+1:

**Comment by alexandre-mbm** [comment]
Yes, it seems. :+1:

**Comment by alexandre-mbm** [comment]
Yes, here also. :+1:

**Comment by govvin** [comment]
Couldn't login OSMCHA again.

![image](https://cloud.githubusercontent.com/assets/5821688/26479990/a2880de8-4209-11e7-9003-23100dcafadb.png)

**Comment by batpad** [comment]
👋 @govvin - so sorry for this -- this will be fixed properly in the new version that we are hopefully pretty close to releasing.

In the meanwhile, if you use `https://` login should definitely work:

So, if you go to: https://osmcha.mapbox.com and then login, it should all work fine. Please let us know if something is still broken for you. Again, we hope to fix this properly in the new version so that there isn't this confusion. Thank you for reporting!

**Comment by willemarcel** [comment]
The frontend is redirecting the users to https:// now.
