### ISSUE TITLE
Changeset Analysis colour is wrong

### ISSUE THREAD

**Issue by james2432** [willemarcel/osmcha-django#62]
Take for example:
http://osmcha.mapbox.com/46284905/
http://osmcha.mapbox.com/46284826/
http://osmcha.mapbox.com/46284752/
http://osmcha.mapbox.com/46284678/
http://osmcha.mapbox.com/46284616/
http://osmcha.mapbox.com/46284547/

Which were all part of 1 upload. If you look at them individually, it looks like there's a massive delete occurring, which isn't the case, it's data that's being added. The added data needs to be split among multiple changesets as the new cap is 10000 objects. I don't blame anyone glancing at these changesets and seeing a massive deletion to flag it as harmful.

**Comment by DenisCarriere** [comment]
![image](https://cloud.githubusercontent.com/assets/550895/23223324/c6a69316-f8f8-11e6-9544-02741be0f08c.png)

**Comment by james2432** [comment]
What is actually going on(creation and adding to the relations):
https://overpass-api.de/achavi/?changeset=46284752
![image](https://cloud.githubusercontent.com/assets/498547/23223963/95e20286-f8fa-11e6-8af6-14bbc5c63ae8.png)

**Comment by willemarcel** [comment]
Hi @james2432!

I believe it's a problem of https://github.com/osmlab/changeset-map/

We use it to visualize the changeset on OSMCHA.

**Comment by james2432** [comment]
Seems to be fixed now

**Comment by batpad** [comment]
We just made some fixes on https://github.com/osmlab/changeset-map/ that should make it both, quicker to load, as well as more reliable in what it displays. The root cause was trying to process JSON from Overpass, which was causing us to lose some information - we have switched to XML and also using a cache for the diffs to try and make it faster.

Thanks again for reporting the issue @james2432 and please do report anything else you see. Cheers!

**Comment by geohacker** [comment]
@ajithranka 👏 👏
