### ISSUE TITLE
Lets have Harmful changesets toggle as mandatory

### ISSUE THREAD

**Issue by manoharuss** [willemarcel/osmcha-django#73]
![image](https://cloud.githubusercontent.com/assets/8921295/24233237/ebaf220c-0fb6-11e7-9c31-cfc62c7ea7c8.png)

This toggle needs to be mandatory. 

cc @willemarcel @amishas157 @batpad

**Comment by batpad** [comment]
Oh, that looks like a bug - I think the `all` option should get selected by default.

@manoharuss - is this affecting work-flows though? And if so, could you say how? Since we are focusing on the API and are going to re-work the frontend entirely, I'd like to keep front-end fixes at the moment to a bare minimum of critical bugfixes. Thank you.

**Comment by manoharuss** [comment]
@batpad this is not a blocker for workflows. Just a small bug at this point. Lets prioritize this later.
