### ISSUE TITLE
Function to regularly fetch latest changesets

### ISSUE THREAD

**Issue by batpad** [willemarcel/osmcha-django#8]
This would need:
- [x] Populate `Import` model with `start` and `end` of changesets imported
- [ ] Setup a `celery` scheduled task to check latest sequence id on planet.openstreetmap.org
- [x] Fetch all changesets between last `end` in `Import` model and current sequence id

@willemarcel does the above make sense? I am working on a PR towards the same. Will link to this issue when done. 

Refs #2

**Comment by willemarcel** [comment]
yes, it's exactly what we need now!

**Comment by batpad** [comment]
This seems almost implemented - to set this up as a `celery` scheduled task, I was able to add something like this to settings:

    CELERYBEAT_SCHEDULE = {
        'schedule-name': {
            'task': 'osmchadjango.changeset.tasks.fetch_latest',
            'schedule': 60 #Run every 60 seconds
        },
    }

And then start the `celery` process with:

    celery -B -A config worker -l info

While this works, I do not have enough experience with `celery` and `rabbitmq` to know if this is the best way to do things, or if this is desirable. I am not sure if that setting should go into `config/settings/common.py` or just be part of documentation. @willemarcel thoughts?

**Comment by willemarcel** [comment]
I used to put the schedule on the celery.py file, but this week I discovered that it's not a good practice because someone should need another frequency of updates http://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html#starting-the-scheduler

So I think it's better to put your CELERYBEAT_SCHEDULE example on the documentation.
