### ISSUE TITLE
Suspicious edit flagging is not appropriate 

### ISSUE THREAD

**Issue by Vaomatua** [willemarcel/osmcha-django#82]
Most of the edits I make to OSM get flagged as [suspicious](http://osmcha.mapbox.com/?usernames=Palolo&is_suspect=True&is_whitelisted=True&checked=All&all_reason=True). 
I think this could be due to the current state of OSM mapping here in Ethiopia compared to other parts of the world where the database is more complete.  I have never imported geospatial features with this account (Palolo) but yet most edits are flagged as "Possible import".  Additionally there are many places in Ethiopia that have not been tagged, are misplaced, or have incorrect tags. Could the logic be changed based on feature density, HOT projects, or should I not worry about the way my edits are flagged?

**Comment by batpad** [comment]
I think we should maybe change the wording here - things are not so much `suspicious` as "tagged to maybe review" - of course, all changesets that import a large number of items are not suspicious, but, there is a strong use case to be able to see all changesets in my area that maybe importing a large number of items to watch out for possible bad imports.

We are working on more attributes like the type of feature edits in the changeset, but I think this could also be greatly helped by not calling it `suspicious` and scaring people off :-)

@willemarcel @planemad @geohacker @rasagy - do you think we could the "suspicious reasons" something a bit more friendly and broad, to clarify their purpose, more as "changeset labelling" for people who maybe interested in reviewing certain types of things.

(Thank you for the inputs here, @Vaomatua ! )

**Comment by Vaomatua** [comment]
Thanks @batpad for the quick response. Perhaps there is some additional logic that could be added to look for imports besides feature count? I often submit edits that have several thousand features, and often more than 10K, all created by hand in JOSM.

**Comment by willemarcel** [comment]
@Vaomatua Thanks for using osmcha and for your report.

@batpad We already have the description field in the `SuspicionReasons` model that we can use to explain better to the users what it means. The 'suspicious' word appears only in the filters, so I don't see it too much scaring. I'll try to ask some users what is the impression they have about it.

**Comment by planemad** [comment]
> do you think we could the "suspicious reasons" something a bit more friendly and broad

`Changeset tags`?

**Comment by Vaomatua** [comment]
I think my point is more to the logic than just the wording. Almost every edit I make has hundreds of features, I am tracing buildings and roads in Africa where nothing is mapped, not adding content to someplace well mapped like the UK or Germany. On OSMCHA my user name has 19 pages of **is_suspect=true**
If I am doing something wrong I would be glad for the feedback, but I don't know how flagging hundreds of legitimate edits helps the OSM community.

**Comment by willemarcel** [comment]
@Vaomatua I agree that a lot of good edits are flagged as suspect. Here in Brazil we always have problems caused by people importing data from illegal sources and copying street names from google maps. When we don't detect and revert those edits early, a lot of people can waste their time making contributions to map data that will be redacted by DWG. Maybe this problem doesn't happen in Africa because there aren't other datasets besides OSM.

It's very difficult to analyse every changeset and its context. So for now I can only ask you to see it not as an indictment that you are doing bad things, but just as a flag that this changeset added a lot of things. If someone wants to review the edits made in Africa this week, probably it will help them to choose which edits could have priority to be reviewed.

**Comment by batpad** [comment]
@Vaomatua - thanks again for the feedback here.

So, when we started the project, the only thing we were inspecting was changeset metadata. I.e. the only thing we were using as a basis for classifying changesets was counts of objects added, mostly. This is because running analysis on every feature is a hard problem, both due to the data structures and complexities with OSM data, as well as the resources required to do this.

Thus, we relied on very simply assumptions based on changeset metadata, to begin to classify changesets, to be able to use as a starting point to discover patterns. When we started, there was really no tool to be able to search for changesets in a particular area, matching certain characteristics.

We are now working on deeper analysis of feature changes - inspecting tag changes, checking the importance of objects changed, and also factoring in "user age" to try and highlight what changesets should be maybe reviewed.

I can totally understand that it is probably a bit disconcerting to see these pages where a bot has flagged your changesets based on some criteria - I assure you the intention here is more to make, for eg. changesets that add a lot of things, easier searchable, and to tag changesets sharing some characteristics to be able to try and figure out what subset of the huge amount of changes in OSM are worth trying to review. The intention is not at all to discourage you from the obviously really good you're doing improving the map, and I do deeply apologize if it comes off as such.

I think we could improve both the logic and the wording / how these lists are presented. We are working on a significant overhaul of the software, and I hope we can present things so that the limitations of the system are clear (it will never be perfect at finding "bad" changes), but also allows us to continue experimenting with tagging changesets, reviewing things, and trying to find better ways to find validation and review processes that help  the community.

cc @rasagy

**Comment by Vaomatua** [comment]
@willemarcel thank you for the explanation, I agree with the notion of keeping OSM open.  Unfortunately it is too easy for people to "borrow" from google. I won't feel indicted.

Would it be possible to select a filter from a country list?  Most countries are not rectangular and when a bounding box is created neighboring country edits show up in the box.

**Comment by willemarcel** [comment]
@Vaomatua Soon we will make it possible to draw polygons or multipolygons to use in the filters and allow the user to save its favourite queries.

**Comment by willemarcel** [comment]
I believe with the new version released this week this issue is solved. The new interface doesn't use the word `suspicious` any more and the api allow the user to filter changesets by any geometry.
